version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - 15432:5432
  php-fpm:
    container_name: php-fpm
    build:
      context: ./php
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ../src/:/var/www/movieworld
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ../src/:/var/www/movieworld
      - ./nginx/nginx.conf/:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
